name: Kaique de Queiroz
author: Kaique de Queiroz
email: kaique_q@live.com
markdown: kramdown
lang: en
permalink: /blog/:year/:month/:day/:title
url:

# Markdown
markdown: kramdown
kramdown:
  auto_ids: false
highlighter: rouge

# Colections
collections:
  projects:
  projectsBR:
  toollist:

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-mentions

# Turns @ into twitter links
jekyll-mentions:
  base_url: https://twitter.com